server:
  port: 8190
#服务注册中心也会将自己作为客户端来尝试注册自己，所以我们要禁用她（心中）的客户端行为
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8090}/eureka/
